app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

employwes:
    type:     rest
    resource: AppBundle\Controller\EmployerController

utilisateur:
        type:     rest
        resource: AppBundle\Controller\utilisateurController
auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController
acme_api_soap_check:
    path: /soap/check
    defaults: { _controller: AppBundle:Soap:check }
_soap:
    path:      /soap
    defaults:  { _controller: AppBundle:Default:index}